<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>TrBlazeUI.Demo.Server</RootNamespace>
    <AssemblyName>TrBlazeUI.Demo.Server</AssemblyName>
    <NoWarn>CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TrBlazeUI.Demo.Shared\TrBlazeUI.Demo.Shared.csproj" />
  </ItemGroup>

</Project>
